# Model arguments
model_name_or_path: hyunseoki/ko-en-llama2-13b
torch_dtype: auto
use_flash_attention_2: true

# LoRA arguments
use_peft: true
lora_r: 64
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj

# Data training arguments
dataset_mixer:
  moseoridev/train_v7: 1.0
dataset_splits:
  - train
preprocessing_num_workers: 32

# SFT trainer config
bf16: true
do_eval: false
evaluation_strategy: epoch
gradient_accumulation_steps: 128
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: llama_v7_recipe
hub_strategy: end
learning_rate: 2.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 4
output_dir: output/llama_v7_recipe
overwrite_output_dir: true
per_device_eval_batch_size: 8
per_device_train_batch_size: 2
push_to_hub: false
report_to:
  - wandb
save_strategy: "epoch"
save_total_limit: 3
seed: 42
weight_decay: 0.1
